# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc86448bb3e4820788b5d259f1d20323"
name = "dragon-bundles"
application_url = "https://arabia-losing-wednesday-superintendent.trycloudflare.com"
embedded = true
handle = "dragon-bundles"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_publications,write_discounts,write_draft_orders,write_files,write_orders,write_products,write_publications,write_files,read_files"

[auth]
redirect_urls = [
  "https://arabia-losing-wednesday-superintendent.trycloudflare.com/auth/callback",
  "https://arabia-losing-wednesday-superintendent.trycloudflare.com/auth/shopify/callback",
  "https://arabia-losing-wednesday-superintendent.trycloudflare.com/api/auth/callback",
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
