# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc86448bb3e4820788b5d259f1d20323"
application_url = "https://paragraph-williams-essence-district.trycloudflare.com"
embedded = true
name = "dragon-bundles"
handle = "dragon-bundles"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://paragraph-williams-essence-district.trycloudflare.com/auth/callback",
  "https://paragraph-williams-essence-district.trycloudflare.com/auth/shopify/callback",
  "https://paragraph-williams-essence-district.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
